services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL}

  mq:
    image: ${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - ./.env
      - ./../.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nats.conf:/nats.conf
    command: -c /nats.conf
    stdin_open: true
    tty: true

